// GENERATED — do not edit by hand.
// Regenerate via: dart run tools/regen_registry.dart (from app repo)
//
// Registers every supported city. Importing this file links ALL city
// correction tables; region packs (e.g. data/india.dart) link a subset.
import 'registry.dart';
import 'abudhabi/corrections.dart' as abudhabi;
import 'accra/corrections.dart' as accra;
import 'addisababa/corrections.dart' as addisababa;
import 'adelaide/corrections.dart' as adelaide;
import 'agra/corrections.dart' as agra;
import 'ahmedabad/corrections.dart' as ahmedabad;
import 'allahabad/corrections.dart' as allahabad;
import 'almaty/corrections.dart' as almaty;
import 'amman/corrections.dart' as amman;
import 'amritsar/corrections.dart' as amritsar;
import 'amsterdam/corrections.dart' as amsterdam;
import 'ankara/corrections.dart' as ankara;
import 'athens/corrections.dart' as athens;
import 'atlanta/corrections.dart' as atlanta;
import 'auckland/corrections.dart' as auckland;
import 'aurangabad/corrections.dart' as aurangabad;
import 'austin/corrections.dart' as austin;
import 'ayodhya/corrections.dart' as ayodhya;
import 'bahrain/corrections.dart' as bahrain;
import 'bangalore/corrections.dart' as bangalore;
import 'bangkok/corrections.dart' as bangkok;
import 'barcelona/corrections.dart' as barcelona;
import 'beijing/corrections.dart' as beijing;
import 'beirut/corrections.dart' as beirut;
import 'berlin/corrections.dart' as berlin;
import 'bhopal/corrections.dart' as bhopal;
import 'bhubaneswar/corrections.dart' as bhubaneswar;
import 'birmingham/corrections.dart' as birmingham;
import 'bogot/corrections.dart' as bogot;
import 'boston/corrections.dart' as boston;
import 'brampton/corrections.dart' as brampton;
import 'brisbane/corrections.dart' as brisbane;
import 'brussels/corrections.dart' as brussels;
import 'bucharest/corrections.dart' as bucharest;
import 'budapest/corrections.dart' as budapest;
import 'buenosaires/corrections.dart' as buenosaires;
import 'cairo/corrections.dart' as cairo;
import 'calgary/corrections.dart' as calgary;
import 'canberra/corrections.dart' as canberra;
import 'capetown/corrections.dart' as capetown;
import 'chandigarh/corrections.dart' as chandigarh;
import 'charlotte/corrections.dart' as charlotte;
import 'chennai/corrections.dart' as chennai;
import 'chicago/corrections.dart' as chicago;
import 'coimbatore/corrections.dart' as coimbatore;
import 'colombo/corrections.dart' as colombo;
import 'columbus/corrections.dart' as columbus;
import 'copenhagen/corrections.dart' as copenhagen;
import 'dallas/corrections.dart' as dallas;
import 'daressalaam/corrections.dart' as daressalaam;
import 'dehradun/corrections.dart' as dehradun;
import 'delhi/corrections.dart' as delhi;
import 'denpasar/corrections.dart' as denpasar;
import 'denver/corrections.dart' as denver;
import 'detroit/corrections.dart' as detroit;
import 'dhaka/corrections.dart' as dhaka;
import 'doha/corrections.dart' as doha;
import 'dubai/corrections.dart' as dubai;
import 'dublin/corrections.dart' as dublin;
import 'durban/corrections.dart' as durban;
import 'dwarka/corrections.dart' as dwarka;
import 'edinburgh/corrections.dart' as edinburgh;
import 'edmonton/corrections.dart' as edmonton;
import 'faridabad/corrections.dart' as faridabad;
import 'fremont/corrections.dart' as fremont;
import 'georgetown/corrections.dart' as georgetown;
import 'ghaziabad/corrections.dart' as ghaziabad;
import 'glasgow/corrections.dart' as glasgow;
import 'gorakhpur/corrections.dart' as gorakhpur;
import 'gothenburg/corrections.dart' as gothenburg;
import 'gurgaon/corrections.dart' as gurgaon;
import 'guwahati/corrections.dart' as guwahati;
import 'gwalior/corrections.dart' as gwalior;
import 'halifax/corrections.dart' as halifax;
import 'hanoi/corrections.dart' as hanoi;
import 'haridwar/corrections.dart' as haridwar;
import 'helsinki/corrections.dart' as helsinki;
import 'hochiminhcity/corrections.dart' as hochiminhcity;
import 'hongkong/corrections.dart' as hongkong;
import 'honolulu/corrections.dart' as honolulu;
import 'houston/corrections.dart' as houston;
import 'hubli/corrections.dart' as hubli;
import 'hyderabad/corrections.dart' as hyderabad;
import 'indianapolis/corrections.dart' as indianapolis;
import 'indore/corrections.dart' as indore;
import 'islamabad/corrections.dart' as islamabad;
import 'istanbul/corrections.dart' as istanbul;
import 'jabalpur/corrections.dart' as jabalpur;
import 'jaipur/corrections.dart' as jaipur;
import 'jakarta/corrections.dart' as jakarta;
import 'jalandhar/corrections.dart' as jalandhar;
import 'jammu/corrections.dart' as jammu;
import 'jeddah/corrections.dart' as jeddah;
import 'jodhpur/corrections.dart' as jodhpur;
import 'johannesburg/corrections.dart' as johannesburg;
import 'kampala/corrections.dart' as kampala;
import 'kanpur/corrections.dart' as kanpur;
import 'kansascity/corrections.dart' as kansascity;
import 'karachi/corrections.dart' as karachi;
import 'kathmandu/corrections.dart' as kathmandu;
import 'kingston/corrections.dart' as kingston;
import 'kirkland/corrections.dart' as kirkland;
import 'kochi/corrections.dart' as kochi;
import 'kolkata/corrections.dart' as kolkata;
import 'kota/corrections.dart' as kota;
import 'krakow/corrections.dart' as krakow;
import 'kualalumpur/corrections.dart' as kualalumpur;
import 'kuwaitcity/corrections.dart' as kuwaitcity;
import 'kyiv/corrections.dart' as kyiv;
import 'lagos/corrections.dart' as lagos;
import 'lahore/corrections.dart' as lahore;
import 'lasvegas/corrections.dart' as lasvegas;
import 'leicester/corrections.dart' as leicester;
import 'lima/corrections.dart' as lima;
import 'lisbon/corrections.dart' as lisbon;
import 'london/corrections.dart' as london;
import 'losangeles/corrections.dart' as losangeles;
import 'lucknow/corrections.dart' as lucknow;
import 'ludhiana/corrections.dart' as ludhiana;
import 'lyon/corrections.dart' as lyon;
import 'madrid/corrections.dart' as madrid;
import 'madurai/corrections.dart' as madurai;
import 'manchester/corrections.dart' as manchester;
import 'mangalore/corrections.dart' as mangalore;
import 'manila/corrections.dart' as manila;
import 'mathura/corrections.dart' as mathura;
import 'medellin/corrections.dart' as medellin;
import 'meerut/corrections.dart' as meerut;
import 'melbourne/corrections.dart' as melbourne;
import 'mexicocity/corrections.dart' as mexicocity;
import 'miami/corrections.dart' as miami;
import 'milan/corrections.dart' as milan;
import 'minneapolis/corrections.dart' as minneapolis;
import 'mississauga/corrections.dart' as mississauga;
import 'mombasa/corrections.dart' as mombasa;
import 'montreal/corrections.dart' as montreal;
import 'moscow/corrections.dart' as moscow;
import 'mumbai/corrections.dart' as mumbai;
import 'munich/corrections.dart' as munich;
import 'muscat/corrections.dart' as muscat;
import 'mussoorie/corrections.dart' as mussoorie;
import 'mysore/corrections.dart' as mysore;
import 'nagpur/corrections.dart' as nagpur;
import 'nairobi/corrections.dart' as nairobi;
import 'naples/corrections.dart' as naples;
import 'nashik/corrections.dart' as nashik;
import 'nashville/corrections.dart' as nashville;
import 'newyork/corrections.dart' as newyork;
import 'noida/corrections.dart' as noida;
import 'orlando/corrections.dart' as orlando;
import 'osaka/corrections.dart' as osaka;
import 'oslo/corrections.dart' as oslo;
import 'ottawa/corrections.dart' as ottawa;
import 'panamacity/corrections.dart' as panamacity;
import 'paramaribo/corrections.dart' as paramaribo;
import 'paris/corrections.dart' as paris;
import 'patna/corrections.dart' as patna;
import 'perth/corrections.dart' as perth;
import 'philadelphia/corrections.dart' as philadelphia;
import 'phnompenh/corrections.dart' as phnompenh;
import 'phoenix/corrections.dart' as phoenix;
import 'pittsburgh/corrections.dart' as pittsburgh;
import 'portland/corrections.dart' as portland;
import 'portlouis/corrections.dart' as portlouis;
import 'porto/corrections.dart' as porto;
import 'portofspain/corrections.dart' as portofspain;
import 'prague/corrections.dart' as prague;
import 'prayagraj/corrections.dart' as prayagraj;
import 'pune/corrections.dart' as pune;
import 'quito/corrections.dart' as quito;
import 'raipur/corrections.dart' as raipur;
import 'rajkot/corrections.dart' as rajkot;
import 'raleigh/corrections.dart' as raleigh;
import 'ranchi/corrections.dart' as ranchi;
import 'redmond/corrections.dart' as redmond;
import 'regina/corrections.dart' as regina;
import 'riodejaneiro/corrections.dart' as riodejaneiro;
import 'rishikesh/corrections.dart' as rishikesh;
import 'riyadh/corrections.dart' as riyadh;
import 'rome/corrections.dart' as rome;
import 'rotterdam/corrections.dart' as rotterdam;
import 'sacramento/corrections.dart' as sacramento;
import 'salem/corrections.dart' as salem;
import 'saltlakecity/corrections.dart' as saltlakecity;
import 'sandiego/corrections.dart' as sandiego;
import 'sanfrancisco/corrections.dart' as sanfrancisco;
import 'sanjose/corrections.dart' as sanjose;
import 'santiago/corrections.dart' as santiago;
import 'seattle/corrections.dart' as seattle;
import 'seoul/corrections.dart' as seoul;
import 'shanghai/corrections.dart' as shanghai;
import 'shirdi/corrections.dart' as shirdi;
import 'singapore/corrections.dart' as singapore;
import 'sofia/corrections.dart' as sofia;
import 'sopaulo/corrections.dart' as sopaulo;
import 'srinagar/corrections.dart' as srinagar;
import 'stlouis/corrections.dart' as stlouis;
import 'stockholm/corrections.dart' as stockholm;
import 'surat/corrections.dart' as surat;
import 'surrey/corrections.dart' as surrey;
import 'suva/corrections.dart' as suva;
import 'sydney/corrections.dart' as sydney;
import 'taipei/corrections.dart' as taipei;
import 'tampa/corrections.dart' as tampa;
import 'tashkent/corrections.dart' as tashkent;
import 'telaviv/corrections.dart' as telaviv;
import 'thane/corrections.dart' as thane;
import 'thessaloniki/corrections.dart' as thessaloniki;
import 'thiruvananthapuram/corrections.dart' as thiruvananthapuram;
import 'tiruchirappalli/corrections.dart' as tiruchirappalli;
import 'tirupati/corrections.dart' as tirupati;
import 'tokyo/corrections.dart' as tokyo;
import 'toronto/corrections.dart' as toronto;
import 'udaipur/corrections.dart' as udaipur;
import 'ujjain/corrections.dart' as ujjain;
import 'vadodara/corrections.dart' as vadodara;
import 'vancouver/corrections.dart' as vancouver;
import 'varanasi/corrections.dart' as varanasi;
import 'vienna/corrections.dart' as vienna;
import 'vijayawada/corrections.dart' as vijayawada;
import 'visakhapatnam/corrections.dart' as visakhapatnam;
import 'vrindavan/corrections.dart' as vrindavan;
import 'warangal/corrections.dart' as warangal;
import 'warsaw/corrections.dart' as warsaw;
import 'washingtondc/corrections.dart' as washingtondc;
import 'wellington/corrections.dart' as wellington;
import 'winnipeg/corrections.dart' as winnipeg;
import 'yangon/corrections.dart' as yangon;
import 'zagreb/corrections.dart' as zagreb;
import 'zurich/corrections.dart' as zurich;

/// Register all 230 supported cities.
bool _registered = false;
void registerAllCities() {
  if (_registered) return; // idempotent: register once
  _registered = true;
  registerCity('Abu Dhabi', tithi: abudhabi.abudhabiTithiCorrections);
  registerCity('Accra', tithi: accra.accraTithiCorrections);
  registerCity('Addis Ababa', tithi: addisababa.addisababaTithiCorrections);
  registerCity('Adelaide', tithi: adelaide.adelaideTithiCorrections);
  registerCity('Agra', tithi: agra.agraTithiCorrections);
  registerCity('Ahmedabad', tithi: ahmedabad.ahmedabadTithiCorrections);
  registerCity('Allahabad', tithi: allahabad.allahabadTithiCorrections);
  registerCity('Almaty', tithi: almaty.almatyTithiCorrections);
  registerCity('Amman', tithi: amman.ammanTithiCorrections);
  registerCity('Amritsar', tithi: amritsar.amritsarTithiCorrections);
  registerCity('Amsterdam', tithi: amsterdam.amsterdamTithiCorrections);
  registerCity('Ankara', tithi: ankara.ankaraTithiCorrections);
  registerCity('Athens', tithi: athens.athensTithiCorrections);
  registerCity('Atlanta', tithi: atlanta.atlantaTithiCorrections);
  registerCity('Auckland', tithi: auckland.aucklandTithiCorrections);
  registerCity('Aurangabad', tithi: aurangabad.aurangabadTithiCorrections);
  registerCity('Austin', tithi: austin.austinTithiCorrections);
  registerCity('Ayodhya', tithi: ayodhya.ayodhyaTithiCorrections);
  registerCity('Bahrain', tithi: bahrain.bahrainTithiCorrections);
  registerCity('Bangalore', tithi: bangalore.bangaloreTithiCorrections);
  registerCity('Bangkok', tithi: bangkok.bangkokTithiCorrections);
  registerCity('Barcelona', tithi: barcelona.barcelonaTithiCorrections);
  registerCity('Beijing', tithi: beijing.beijingTithiCorrections);
  registerCity('Beirut', tithi: beirut.beirutTithiCorrections);
  registerCity('Berlin', tithi: berlin.berlinTithiCorrections);
  registerCity('Bhopal', tithi: bhopal.bhopalTithiCorrections);
  registerCity('Bhubaneswar', tithi: bhubaneswar.bhubaneswarTithiCorrections);
  registerCity('Birmingham', tithi: birmingham.birminghamTithiCorrections);
  registerCity('Bogotá', tithi: bogot.bogotTithiCorrections);
  registerCity('Boston', tithi: boston.bostonTithiCorrections);
  registerCity('Brampton', tithi: brampton.bramptonTithiCorrections);
  registerCity('Brisbane', tithi: brisbane.brisbaneTithiCorrections);
  registerCity('Brussels', tithi: brussels.brusselsTithiCorrections);
  registerCity('Bucharest', tithi: bucharest.bucharestTithiCorrections);
  registerCity('Budapest', tithi: budapest.budapestTithiCorrections);
  registerCity('Buenos Aires', tithi: buenosaires.buenosairesTithiCorrections);
  registerCity('Cairo', tithi: cairo.cairoTithiCorrections);
  registerCity('Calgary', tithi: calgary.calgaryTithiCorrections);
  registerCity('Canberra', tithi: canberra.canberraTithiCorrections);
  registerCity('Cape Town', tithi: capetown.capetownTithiCorrections);
  registerCity('Chandigarh', tithi: chandigarh.chandigarhTithiCorrections);
  registerCity('Charlotte', tithi: charlotte.charlotteTithiCorrections);
  registerCity('Chennai', tithi: chennai.chennaiTithiCorrections);
  registerCity('Chicago', tithi: chicago.chicagoTithiCorrections);
  registerCity('Coimbatore', tithi: coimbatore.coimbatoreTithiCorrections);
  registerCity('Colombo', tithi: colombo.colomboTithiCorrections);
  registerCity('Columbus', tithi: columbus.columbusTithiCorrections);
  registerCity('Copenhagen', tithi: copenhagen.copenhagenTithiCorrections);
  registerCity('Dallas', tithi: dallas.dallasTithiCorrections);
  registerCity('Dar es Salaam', tithi: daressalaam.daressalaamTithiCorrections);
  registerCity('Dehradun', tithi: dehradun.dehradunTithiCorrections);
  registerCity('Delhi', tithi: delhi.delhiTithiCorrections);
  registerCity('Denpasar', tithi: denpasar.denpasarTithiCorrections);
  registerCity('Denver', tithi: denver.denverTithiCorrections);
  registerCity('Detroit', tithi: detroit.detroitTithiCorrections);
  registerCity('Dhaka', tithi: dhaka.dhakaTithiCorrections);
  registerCity('Doha', tithi: doha.dohaTithiCorrections);
  registerCity('Dubai', tithi: dubai.dubaiTithiCorrections);
  registerCity('Dublin', tithi: dublin.dublinTithiCorrections);
  registerCity('Durban', tithi: durban.durbanTithiCorrections);
  registerCity('Dwarka', tithi: dwarka.dwarkaTithiCorrections);
  registerCity('Edinburgh', tithi: edinburgh.edinburghTithiCorrections);
  registerCity('Edmonton', tithi: edmonton.edmontonTithiCorrections);
  registerCity('Faridabad', tithi: faridabad.faridabadTithiCorrections);
  registerCity('Fremont', tithi: fremont.fremontTithiCorrections);
  registerCity('Georgetown', tithi: georgetown.georgetownTithiCorrections);
  registerCity('Ghaziabad', tithi: ghaziabad.ghaziabadTithiCorrections);
  registerCity('Glasgow', tithi: glasgow.glasgowTithiCorrections);
  registerCity('Gorakhpur', tithi: gorakhpur.gorakhpurTithiCorrections);
  registerCity('Gothenburg', tithi: gothenburg.gothenburgTithiCorrections);
  registerCity('Gurgaon', tithi: gurgaon.gurgaonTithiCorrections);
  registerCity('Guwahati', tithi: guwahati.guwahatiTithiCorrections);
  registerCity('Gwalior', tithi: gwalior.gwaliorTithiCorrections);
  registerCity('Halifax', tithi: halifax.halifaxTithiCorrections);
  registerCity('Hanoi', tithi: hanoi.hanoiTithiCorrections);
  registerCity('Haridwar', tithi: haridwar.haridwarTithiCorrections);
  registerCity('Helsinki', tithi: helsinki.helsinkiTithiCorrections);
  registerCity('Ho Chi Minh City',
      tithi: hochiminhcity.hochiminhcityTithiCorrections);
  registerCity('Hong Kong', tithi: hongkong.hongkongTithiCorrections);
  registerCity('Honolulu', tithi: honolulu.honoluluTithiCorrections);
  registerCity('Houston', tithi: houston.houstonTithiCorrections);
  registerCity('Hubli', tithi: hubli.hubliTithiCorrections);
  registerCity('Hyderabad', tithi: hyderabad.hyderabadTithiCorrections);
  registerCity('Indianapolis',
      tithi: indianapolis.indianapolisTithiCorrections);
  registerCity('Indore', tithi: indore.indoreTithiCorrections);
  registerCity('Islamabad', tithi: islamabad.islamabadTithiCorrections);
  registerCity('Istanbul', tithi: istanbul.istanbulTithiCorrections);
  registerCity('Jabalpur', tithi: jabalpur.jabalpurTithiCorrections);
  registerCity('Jaipur', tithi: jaipur.jaipurTithiCorrections);
  registerCity('Jakarta', tithi: jakarta.jakartaTithiCorrections);
  registerCity('Jalandhar', tithi: jalandhar.jalandharTithiCorrections);
  registerCity('Jammu', tithi: jammu.jammuTithiCorrections);
  registerCity('Jeddah', tithi: jeddah.jeddahTithiCorrections);
  registerCity('Jodhpur', tithi: jodhpur.jodhpurTithiCorrections);
  registerCity('Johannesburg',
      tithi: johannesburg.johannesburgTithiCorrections);
  registerCity('Kampala', tithi: kampala.kampalaTithiCorrections);
  registerCity('Kanpur', tithi: kanpur.kanpurTithiCorrections);
  registerCity('Kansas City', tithi: kansascity.kansascityTithiCorrections);
  registerCity('Karachi', tithi: karachi.karachiTithiCorrections);
  registerCity('Kathmandu', tithi: kathmandu.kathmanduTithiCorrections);
  registerCity('Kingston', tithi: kingston.kingstonTithiCorrections);
  registerCity('Kirkland', tithi: kirkland.kirklandTithiCorrections);
  registerCity('Kochi', tithi: kochi.kochiTithiCorrections);
  registerCity('Kolkata', tithi: kolkata.kolkataTithiCorrections);
  registerCity('Kota', tithi: kota.kotaTithiCorrections);
  registerCity('Krakow', tithi: krakow.krakowTithiCorrections);
  registerCity('Kuala Lumpur', tithi: kualalumpur.kualalumpurTithiCorrections);
  registerCity('Kuwait City', tithi: kuwaitcity.kuwaitcityTithiCorrections);
  registerCity('Kyiv', tithi: kyiv.kyivTithiCorrections);
  registerCity('Lagos', tithi: lagos.lagosTithiCorrections);
  registerCity('Lahore', tithi: lahore.lahoreTithiCorrections);
  registerCity('Las Vegas', tithi: lasvegas.lasvegasTithiCorrections);
  registerCity('Leicester', tithi: leicester.leicesterTithiCorrections);
  registerCity('Lima', tithi: lima.limaTithiCorrections);
  registerCity('Lisbon', tithi: lisbon.lisbonTithiCorrections);
  registerCity('London', tithi: london.londonTithiCorrections);
  registerCity('Los Angeles', tithi: losangeles.losangelesTithiCorrections);
  registerCity('Lucknow', tithi: lucknow.lucknowTithiCorrections);
  registerCity('Ludhiana', tithi: ludhiana.ludhianaTithiCorrections);
  registerCity('Lyon', tithi: lyon.lyonTithiCorrections);
  registerCity('Madrid', tithi: madrid.madridTithiCorrections);
  registerCity('Madurai', tithi: madurai.maduraiTithiCorrections);
  registerCity('Manchester', tithi: manchester.manchesterTithiCorrections);
  registerCity('Mangalore', tithi: mangalore.mangaloreTithiCorrections);
  registerCity('Manila', tithi: manila.manilaTithiCorrections);
  registerCity('Mathura', tithi: mathura.mathuraTithiCorrections);
  registerCity('Medellín', tithi: medellin.medellinTithiCorrections);
  registerCity('Meerut', tithi: meerut.meerutTithiCorrections);
  registerCity('Melbourne', tithi: melbourne.melbourneTithiCorrections);
  registerCity('Mexico City', tithi: mexicocity.mexicocityTithiCorrections);
  registerCity('Miami', tithi: miami.miamiTithiCorrections);
  registerCity('Milan', tithi: milan.milanTithiCorrections);
  registerCity('Minneapolis', tithi: minneapolis.minneapolisTithiCorrections);
  registerCity('Mississauga', tithi: mississauga.mississaugaTithiCorrections);
  registerCity('Mombasa', tithi: mombasa.mombasaTithiCorrections);
  registerCity('Montreal', tithi: montreal.montrealTithiCorrections);
  registerCity('Moscow', tithi: moscow.moscowTithiCorrections);
  registerCity('Mumbai', tithi: mumbai.mumbaiTithiCorrections);
  registerCity('Munich', tithi: munich.munichTithiCorrections);
  registerCity('Muscat', tithi: muscat.muscatTithiCorrections);
  registerCity('Mussoorie', tithi: mussoorie.mussoorieTithiCorrections);
  registerCity('Mysore', tithi: mysore.mysoreTithiCorrections);
  registerCity('Nagpur', tithi: nagpur.nagpurTithiCorrections);
  registerCity('Nairobi', tithi: nairobi.nairobiTithiCorrections);
  registerCity('Naples', tithi: naples.naplesTithiCorrections);
  registerCity('Nashik', tithi: nashik.nashikTithiCorrections);
  registerCity('Nashville', tithi: nashville.nashvilleTithiCorrections);
  registerCity('New York', tithi: newyork.newyorkTithiCorrections);
  registerCity('Noida', tithi: noida.noidaTithiCorrections);
  registerCity('Orlando', tithi: orlando.orlandoTithiCorrections);
  registerCity('Osaka', tithi: osaka.osakaTithiCorrections);
  registerCity('Oslo', tithi: oslo.osloTithiCorrections);
  registerCity('Ottawa', tithi: ottawa.ottawaTithiCorrections);
  registerCity('Panama City', tithi: panamacity.panamacityTithiCorrections);
  registerCity('Paramaribo', tithi: paramaribo.paramariboTithiCorrections);
  registerCity('Paris', tithi: paris.parisTithiCorrections);
  registerCity('Patna', tithi: patna.patnaTithiCorrections);
  registerCity('Perth', tithi: perth.perthTithiCorrections);
  registerCity('Philadelphia',
      tithi: philadelphia.philadelphiaTithiCorrections);
  registerCity('Phnom Penh', tithi: phnompenh.phnompenhTithiCorrections);
  registerCity('Phoenix', tithi: phoenix.phoenixTithiCorrections);
  registerCity('Pittsburgh', tithi: pittsburgh.pittsburghTithiCorrections);
  registerCity('Portland', tithi: portland.portlandTithiCorrections);
  registerCity('Port Louis', tithi: portlouis.portlouisTithiCorrections);
  registerCity('Porto', tithi: porto.portoTithiCorrections);
  registerCity('Port of Spain', tithi: portofspain.portofspainTithiCorrections);
  registerCity('Prague', tithi: prague.pragueTithiCorrections);
  registerCity('Prayagraj', tithi: prayagraj.prayagrajTithiCorrections);
  registerCity('Pune', tithi: pune.puneTithiCorrections);
  registerCity('Quito', tithi: quito.quitoTithiCorrections);
  registerCity('Raipur', tithi: raipur.raipurTithiCorrections);
  registerCity('Rajkot', tithi: rajkot.rajkotTithiCorrections);
  registerCity('Raleigh', tithi: raleigh.raleighTithiCorrections);
  registerCity('Ranchi', tithi: ranchi.ranchiTithiCorrections);
  registerCity('Redmond', tithi: redmond.redmondTithiCorrections);
  registerCity('Regina', tithi: regina.reginaTithiCorrections);
  registerCity('Rio de Janeiro',
      tithi: riodejaneiro.riodejaneiroTithiCorrections);
  registerCity('Rishikesh', tithi: rishikesh.rishikeshTithiCorrections);
  registerCity('Riyadh', tithi: riyadh.riyadhTithiCorrections);
  registerCity('Rome', tithi: rome.romeTithiCorrections);
  registerCity('Rotterdam', tithi: rotterdam.rotterdamTithiCorrections);
  registerCity('Sacramento', tithi: sacramento.sacramentoTithiCorrections);
  registerCity('Salem', tithi: salem.salemTithiCorrections);
  registerCity('Salt Lake City',
      tithi: saltlakecity.saltlakecityTithiCorrections);
  registerCity('San Diego', tithi: sandiego.sandiegoTithiCorrections);
  registerCity('San Francisco',
      tithi: sanfrancisco.sanfranciscoTithiCorrections);
  registerCity('San Jose', tithi: sanjose.sanjoseTithiCorrections);
  registerCity('Santiago', tithi: santiago.santiagoTithiCorrections);
  registerCity('Seattle', tithi: seattle.seattleTithiCorrections);
  registerCity('Seoul', tithi: seoul.seoulTithiCorrections);
  registerCity('Shanghai', tithi: shanghai.shanghaiTithiCorrections);
  registerCity('Shirdi', tithi: shirdi.shirdiTithiCorrections);
  registerCity('Singapore', tithi: singapore.singaporeTithiCorrections);
  registerCity('Sofia', tithi: sofia.sofiaTithiCorrections);
  registerCity('São Paulo', tithi: sopaulo.sopauloTithiCorrections);
  registerCity('Srinagar', tithi: srinagar.srinagarTithiCorrections);
  registerCity('St. Louis', tithi: stlouis.stlouisTithiCorrections);
  registerCity('Stockholm', tithi: stockholm.stockholmTithiCorrections);
  registerCity('Surat', tithi: surat.suratTithiCorrections);
  registerCity('Surrey', tithi: surrey.surreyTithiCorrections);
  registerCity('Suva', tithi: suva.suvaTithiCorrections);
  registerCity('Sydney', tithi: sydney.sydneyTithiCorrections);
  registerCity('Taipei', tithi: taipei.taipeiTithiCorrections);
  registerCity('Tampa', tithi: tampa.tampaTithiCorrections);
  registerCity('Tashkent', tithi: tashkent.tashkentTithiCorrections);
  registerCity('Tel Aviv', tithi: telaviv.telavivTithiCorrections);
  registerCity('Thane', tithi: thane.thaneTithiCorrections);
  registerCity('Thessaloniki',
      tithi: thessaloniki.thessalonikiTithiCorrections);
  registerCity('Thiruvananthapuram',
      tithi: thiruvananthapuram.thiruvananthapuramTithiCorrections);
  registerCity('Tiruchirappalli',
      tithi: tiruchirappalli.tiruchirappalliTithiCorrections);
  registerCity('Tirupati', tithi: tirupati.tirupatiTithiCorrections);
  registerCity('Tokyo', tithi: tokyo.tokyoTithiCorrections);
  registerCity('Toronto', tithi: toronto.torontoTithiCorrections);
  registerCity('Udaipur', tithi: udaipur.udaipurTithiCorrections);
  registerCity('Ujjain', tithi: ujjain.ujjainTithiCorrections);
  registerCity('Vadodara', tithi: vadodara.vadodaraTithiCorrections);
  registerCity('Vancouver', tithi: vancouver.vancouverTithiCorrections);
  registerCity('Varanasi', tithi: varanasi.varanasiTithiCorrections);
  registerCity('Vienna', tithi: vienna.viennaTithiCorrections);
  registerCity('Vijayawada', tithi: vijayawada.vijayawadaTithiCorrections);
  registerCity('Visakhapatnam',
      tithi: visakhapatnam.visakhapatnamTithiCorrections);
  registerCity('Vrindavan', tithi: vrindavan.vrindavanTithiCorrections);
  registerCity('Warangal', tithi: warangal.warangalTithiCorrections);
  registerCity('Warsaw', tithi: warsaw.warsawTithiCorrections);
  registerCity('Washington DC',
      tithi: washingtondc.washingtondcTithiCorrections);
  registerCity('Wellington', tithi: wellington.wellingtonTithiCorrections);
  registerCity('Winnipeg', tithi: winnipeg.winnipegTithiCorrections);
  registerCity('Yangon', tithi: yangon.yangonTithiCorrections);
  registerCity('Zagreb', tithi: zagreb.zagrebTithiCorrections);
  registerCity('Zurich', tithi: zurich.zurichTithiCorrections);
}
